import React from "react";
import { Link } from "react-router-dom";

const FondantFigureGallery = () => {
  const images = [
    "/theme/fondantfigure/img-1.jpg",
    "/theme/fondantfigure/img-2.jpg",
    "/theme/fondantfigure/img-3.jpg",
    "/theme/fondantfigure/img-4.jpg",
    "/theme/fondantfigure/img-5.jpg",
    "/theme/fondantfigure/img-6.jpg",
    "/theme/fondantfigure/img-7.jpg",
    "/theme/fondantfigure/img-8.jpg",
    "/theme/fondantfigure/img-9.jpg",
    "/theme/fondantfigure/img-10.jpg",
    "/theme/fondantfigure/img-11.jpg",
    "/theme/fondantfigure/img-12.jpg",
    "/theme/fondantfigure/img-13.jpg",
    "/theme/fondantfigure/img-14.jpg",
    "/theme/fondantfigure/img-15.jpg",
    "/theme/fondantfigure/img-16.jpg",
    "/theme/fondantfigure/img-17.jpg",
    "/theme/fondantfigure/img-18.jpg",
    "/theme/fondantfigure/img-19.jpg",
    "/theme/fondantfigure/img-20.jpg",
    "/theme/fondantfigure/img-21.jpg",
    "/theme/fondantfigure/img-22.jpg",
    "/theme/fondantfigure/img-23.jpg",
    "/theme/fondantfigure/img-24.jpg",
    "/theme/fondantfigure/img-25.jpg",
    "/theme/fondantfigure/img-26.jpg",
    "/theme/fondantfigure/img-27.jpg",
    "/theme/fondantfigure/img-28.jpg",
    "/theme/fondantfigure/img-29.jpg",
    "/theme/fondantfigure/img-30.jpg",
    "/theme/fondantfigure/img-31.jpg",
    "/theme/fondantfigure/img-32.jpg",
    "/theme/fondantfigure/img-33.jpg",
    "/theme/fondantfigure/img-34.jpg",
    "/theme/fondantfigure/img-35.jpg",
    "/theme/fondantfigure/img-36.jpg",
    "/theme/fondantfigure/img-37.jpg",
    "/theme/fondantfigure/img-38.jpg",
    "/theme/fondantfigure/img-39.jpg",
    "/theme/fondantfigure/img-40.jpg",
    "/theme/fondantfigure/img-41.jpg",
    "/theme/fondantfigure/img-42.jpg",
    "/theme/fondantfigure/img-43.jpg",
    "/theme/fondantfigure/img-44.jpg",
    "/theme/fondantfigure/img-45.jpg",
    "/theme/fondantfigure/img-46.jpg",
    "/theme/fondantfigure/img-47.jpg",
    "/theme/fondantfigure/img-48.jpg",
    "/theme/fondantfigure/img-49.jpg",
    "/theme/fondantfigure/img-50.jpg",
    "/theme/fondantfigure/img-51.jpg",
    "/theme/fondantfigure/img-52.jpg",
    "/theme/fondantfigure/img-53.jpg",
    "/theme/fondantfigure/img-54.jpg",
    "/theme/fondantfigure/img-55.jpg",
    "/theme/fondantfigure/img-56.jpg",
    "/theme/fondantfigure/img-57.jpg",
    "/theme/fondantfigure/img-58.jpg",
    "/theme/fondantfigure/img-59.jpg",
    "/theme/fondantfigure/img-60.jpg",
    "/theme/fondantfigure/img-61.jpg",
    "/theme/fondantfigure/img-62.jpg",
    "/theme/fondantfigure/img-63.jpg",
    "/theme/fondantfigure/img-64.jpg",
    "/theme/fondantfigure/img-65.jpg",
    "/theme/fondantfigure/img-66.jpg",
    "/theme/fondantfigure/img-67.jpg",
    "/theme/fondantfigure/img-68.jpg",
    "/theme/fondantfigure/img-69.jpg",
    "/theme/fondantfigure/img-70.jpg",
    "/theme/fondantfigure/img-71.jpg",
    "/theme/fondantfigure/img-72.jpg",
    "/theme/fondantfigure/img-73.jpg",
    "/theme/fondantfigure/img-74.jpg",
    "/theme/fondantfigure/img-75.jpg",
    "/theme/fondantfigure/img-76.jpg",
    "/theme/fondantfigure/img-77.jpg",
    "/theme/fondantfigure/img-78.jpg",
    "/theme/fondantfigure/img-79.jpg",
    "/theme/fondantfigure/img-80.jpg",
    "/theme/fondantfigure/img-81.jpg",
    "/theme/fondantfigure/img-82.jpg",
    "/theme/fondantfigure/img-83.jpg",
    "/theme/fondantfigure/img-84.jpg",
    "/theme/fondantfigure/img-85.jpg",
    "/theme/fondantfigure/img-86.jpg",
    "/theme/fondantfigure/img-87.jpg",
    "/theme/fondantfigure/img-88.jpg",
    "/theme/fondantfigure/img-89.jpg",
    "/theme/fondantfigure/img-90.jpg",
    "/theme/fondantfigure/img-91.jpg",
    "/theme/fondantfigure/img-92.jpg",
    "/theme/fondantfigure/img-93.jpg",
    "/theme/fondantfigure/img-94.jpg",
    "/theme/fondantfigure/img-95.jpg",
    "/theme/fondantfigure/img-96.jpg",
    "/theme/fondantfigure/img-97.jpg",
    "/theme/fondantfigure/img-98.jpg",
    "/theme/fondantfigure/img-99.jpg",
    "/theme/fondantfigure/img-100.jpg",
    "/theme/fondantfigure/img-101.jpg",
    "/theme/fondantfigure/img-102.jpg",
    "/theme/fondantfigure/img-103.jpg",
    "/theme/fondantfigure/img-104.jpg",
    "/theme/fondantfigure/img-105.jpg",
    "/theme/fondantfigure/img-106.jpg",
    "/theme/fondantfigure/img-107.jpg",
    "/theme/fondantfigure/img-108.jpg",
    "/theme/fondantfigure/img-109.jpg",
    "/theme/fondantfigure/img-110.jpg",
    "/theme/fondantfigure/img-111.jpg",
    "/theme/fondantfigure/img-112.jpg",
    "/theme/fondantfigure/img-113.jpg",
    "/theme/fondantfigure/img-114.jpg",
    "/theme/fondantfigure/img-115.jpg",
    "/theme/fondantfigure/img-116.jpg",
    "/theme/fondantfigure/img-117.jpg",
    "/theme/fondantfigure/img-118.jpg",
    "/theme/fondantfigure/img-119.jpg",
    "/theme/fondantfigure/img-120.jpg",
    "/theme/fondantfigure/img-121.jpg",
    "/theme/fondantfigure/img-122.jpg",
    "/theme/fondantfigure/img-123.jpg",
    "/theme/fondantfigure/img-124.jpg",
    "/theme/fondantfigure/img-125.jpg",
    "/theme/fondantfigure/img-126.jpg",
    "/theme/fondantfigure/img-127.jpg",
    "/theme/fondantfigure/img-128.jpg",
    "/theme/fondantfigure/img-129.jpg",
    "/theme/fondantfigure/img-130.jpg",
    "/theme/fondantfigure/img-131.jpg",
    "/theme/fondantfigure/img-132.jpg",
    "/theme/fondantfigure/img-133.jpg",
    "/theme/fondantfigure/img-134.jpg",
    "/theme/fondantfigure/img-135.jpg",
    "/theme/fondantfigure/img-136.jpg",
    "/theme/fondantfigure/img-137.jpg",
    "/theme/fondantfigure/img-138.jpg",
    "/theme/fondantfigure/img-139.jpg",
    "/theme/fondantfigure/img-140.jpg",
    "/theme/fondantfigure/img-141.jpg",
    "/theme/fondantfigure/img-142.jpg",
    "/theme/fondantfigure/img-143.jpg",
    "/theme/fondantfigure/img-144.jpg",
    "/theme/fondantfigure/img-145.jpg",
    "/theme/fondantfigure/img-146.jpg",
    "/theme/fondantfigure/img-147.jpg",
    "/theme/fondantfigure/img-148.jpg",
    "/theme/fondantfigure/img-149.jpg",
    "/theme/fondantfigure/img-150.jpg",
    "/theme/fondantfigure/img-151.jpg",
    "/theme/fondantfigure/img-152.jpg",
    "/theme/fondantfigure/img-153.jpg",
    "/theme/fondantfigure/img-154.jpg",
    "/theme/fondantfigure/img-155.jpg",
    "/theme/fondantfigure/img-156.jpg",
    "/theme/fondantfigure/img-157.jpg",
    "/theme/fondantfigure/img-158.jpg",
    "/theme/fondantfigure/img-159.jpg"
  ];

  return (
    <div className="min-h-screen bg-pink-50 p-6">
      <h1 className="text-3xl font-bold text-pink-600 mb-8 text-center">
        Special Fondant Figurine Themed Cake Gallery
      </h1>
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 auto-rows-fr">
        {images.map((src, idx) => (
            <div key={idx} className="overflow-hidden rounded-md shadow-lg bg-white flex items-center justify-center aspect-square">
            <img
                src={src}
                alt={`Cake ${idx + 1}`}
                className="object-contain max-h-full"
                loading="lazy"
            />
            </div>
        ))}
       </div>
      <div className="mt-6 text-center">
        <Link to="/" className="text-pink-600 hover:underline">Back to Catalogue</Link>
      </div>
    </div>
  );
};

export default FondantFigureGallery;